schema_version: 1

context:
  name: pysqlscribe
  version: "0.9.1"
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pysqlscribe-${{ version }}.tar.gz
  sha256: cc26b0cabb7d5f5e52de17e56bbf728fff0ca757afa7aeb9a584831fc9b0bcb3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pysqlscribe
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/danielenricocahall/pysqlscribe
  summary: A simple Python Library for building relational database queries using objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
