schema_version: 1

context:
  name: pysqlscribe
  version: "0.8.0"
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pysqlscribe-${{ version }}.tar.gz
  sha256: f05cdf482bd40551c4b26b6651bcbef750f61047c39a01979800a1068dea6d0c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pysqlscribe
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/danielenricocahall/pysqlscribe
  summary: A simple Python Library for building relational database queries using objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
